#!/bin/bash
# List all instances
# Exporting Environment Variables
#########################################
source ./phpqstat.conf
#########################################

qstat -f | grep ethz | awk '{ print $1 " " $2 " " $3 " " $4 " " $5 " " $6}' > $1